base/urls.py
from django.urls import path, re_path, include
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from rest_framework import routers
from .views import CountryViewSet

app_name = 'base'

router = routers.DefaultRouter()
router.register(r'countries', CountryViewSet)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name = 'error_403'),

    path('api/', include(router.urls)),
]

## URLs de peticiones AJAX
urlpatterns += [
    re_path(r'^ajax/combo-update/?$', ComboUpdateView.as_view(), name='combo_update'),
]

user/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from .views import ProfileCreateView, ProfileUpdateView, ProfileDetailView

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset/password_reset/', views.PasswordResetView.as_view(template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html', success_url = reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
        success_url = reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password-change/', login_required(views.PasswordChangeView.as_view(template_name='user/password_change_form.html',
        success_url = reverse_lazy('user:password_change_done'))), name='password_change'),
    path('password-change-done/', login_required(views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html')),
        name='password_change_done'),
    path('profile-create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile-update/<int:pk>/', login_required(ProfileUpdateView.as_view()), name='profile_update'),
    path('profile-detail/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail')
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core import validators

# Create your models here.

class Profile(models.Model):
    """!
    Clase que contiene los datos del perfil de un usuario del sistema

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    ## Teléfono
    phone = models.CharField(
        'teléfono',
        max_length=15,
        validators=[
            validators.RegexValidator(
                r'^\+\d{2}-\d{3}-\d{7}$',
                _("Número telefónico inválido. Solo se permiten números.")
            ),
        ]
    )

    ## Establece la relación entre el usuario del sistema con el perfil
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Usuario')

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Una cadena de caracteres con el nombre y apellido del usuario
        """

        return "%s %s" % (self.user.first_name, self.user.last_name)

    class Meta:
        """!
        Meta clase del modelo que establece algunas propiedades

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        """

        verbose_name = _('Perfil')
        verbose_name_plural = _('Perfiles')

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

class ProfileForm(forms.ModelForm):
    """!
    Clase que contiene los campos del formulario de perfil del usuario

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    ## Username para identificar al usuario
    username = forms.CharField(
        label=_('Nombre de Usuario:'), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _('Indique el nombre de usuario'),
            }
        )
    )

    ## Nombres del usuario
    first_name = forms.CharField(
        label=_('Nombres:'), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _('Indique los Nombres'),
            }
        )
    )

    ## Apellidos del usuario
    last_name = forms.CharField(
        label=_('Apellidos:'), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _('Indique los Apellidos'),
            }
        )
    )

    ## Correo del usuario
    email = forms.EmailField(
        label=_('Correo Electrónico:'), max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control input-sm email-mask', 'data-toggle': 'tooltip',
                'title': _('Indique el correo electrónico')
            }
        )
    )

    ## Teléfono del usuario
    phone = forms.CharField(
        label=_('Teléfono:'), max_length=15,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip', 'placeholder': '+58-000-0000000',
                'data-mask': '+00-000-0000000',
                'title': _('Indique el número telefónico')
            }
        )
    )

    ## Contraseña de acceso del usuario
    password = forms.CharField(
        label=_('Contraseña:'), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _('Indique una contraseña de aceso al sistema')
            }
        )
    )

    ## Confirmación de contraseña de acceso del usuario
    confirm_password = forms.CharField(
        label=_('Confirmar Contraseña:'), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _('Indique nuevamente la contraseña de aceso al sistema')
            }
        )
    )

    def clean_email(self):
        """!
        Función que permite validar si el correo del usuario ya esta registrado en el sistema

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Mensaje de error en caso de que el correo ya esté registrado en el sistema
        """

        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(_('El correo ya esta registrado'))
        return email

    def clean_confirm_password(self):
        """!
        Función que permite validar si ambas contraseñas son iguales

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Mensaje de error en caso de que las contraseñas sean distintas
        """

        confirm_password = self.cleaned_data['confirm_password']
        password = self.cleaned_data.get('password')
        if password != confirm_password:
            raise forms.ValidationError(_('La contraseña no es la misma'))

        return confirm_password

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (paez.william8 at gmail)
        @date 14-01-2018
        """

        model = User
        exclude = ['profile','date_joined']

class ProfileUpdateForm(ProfileForm):
    """!
    Clase que contiene los campos del formulario de perfil del usuario para actualizar los datos

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    def __init__(self, *args, **kwargs):
        """!
        Función que inicializa la clase del formulario para actualizar los datos

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param *args <b>{tupla}</b> Tupla de valores, inicialmente vacia
        @param *kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        """

        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['password'].required = False
        self.fields['confirm_password'].required = False
        self.fields['password'].widget.attrs['disabled'] = True
        self.fields['confirm_password'].widget.attrs['disabled'] = True

    def clean_email(self):
        """!
        función que permite validar el campo de correo electronico

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Mensaje de error en caso de que el correo electronico ya se encuentre registrado
        """

        email = self.cleaned_data['email']
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(_('El correo ya esta registrado'))
        return email

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        """

        model = User
        exclude = [
            'profile','password','confirm_password','date_joined','last_login','is_active','is_superuser','is_staff'
        ]

user/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView
from django.contrib.auth.models import User
from .forms import ProfileForm, ProfileUpdateForm
from .models import Profile
from base.constant import CREATE_MESSAGE, UPDATE_MESSAGE
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.

class ProfileCreateView(SuccessMessageMixin, CreateView):
    """!
    Clase que permite a cualquier persona registrarse en el sistema

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    model = User
    form_class = ProfileForm
    template_name = 'user/profile.create.html'
    success_url = reverse_lazy('user:login')
    success_message = CREATE_MESSAGE

    def form_valid(self, form):
        """!
        Función que valida si el formulario es correcto

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param form <b>{object}</b> Objeto que contiene el formulario de registro
        @return Formulario validado
        """

        self.object = form.save(commit=False)
        self.object.username = form.cleaned_data['username']
        self.object.first_name = form.cleaned_data['first_name']
        self.object.last_name = form.cleaned_data['last_name']
        self.object.email = form.cleaned_data['email']
        self.object.set_password(form.cleaned_data['password'])
        self.object.is_active = True
        self.object.save()

        profile = Profile.objects.create(
            phone = form.cleaned_data['phone'],
            user= self.object
        )

        return super(ProfileCreateView, self).form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super(ProfileCreateView, self).form_invalid(form)

class ProfileUpdateView(SuccessMessageMixin, UpdateView):
    """!
    Clase que permite a un usuario actualizar sus datos de perfil

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    model = User
    form_class = ProfileUpdateForm
    template_name = 'user/profile.create.html'
    success_url = reverse_lazy('base:home')
    success_message = UPDATE_MESSAGE

    def dispatch(self, request, *args, **kwargs):
        """!
        Función que valida si el usuario del sistema tiene permisos para entrar a esta vista

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene la petición
        @param *args <b>{tupla}</b> Tupla de valores, inicialmente vacia
        @param **kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        @return Redirecciona al usuario a la página de error de permisos si no es su perfil
        """

        if self.request.user.id == self.kwargs['pk'] and Profile.objects.filter(user=self.request.user):
            return super(ProfileUpdateView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('base:error_403')

    def get_initial(self):
        """!
        Función que agrega valores predeterminados a los campos del formulario

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Diccionario con los valores predeterminados
        """

        initial_data = super(ProfileUpdateView, self).get_initial()
        initial_data['phone'] = self.object.profile.phone
        return initial_data

    def form_valid(self, form):
        """!
        Función que valida si el formulario es correcto

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param form <b>{object}</b> Objeto que contiene el formulario de registro
        @return Formulario validado
        """

        self.object = form.save(commit=False)
        self.object.username = form.cleaned_data['username']
        self.object.first_name = form.cleaned_data['first_name']
        self.object.last_name = form.cleaned_data['last_name']
        self.object.email = form.cleaned_data['email']
        self.object.save()

        if Profile.objects.filter(user=self.object):
            profile = Profile.objects.get(user=self.object)
            profile.phone = form.cleaned_data['phone']
            profile.save()

        return super(ProfileUpdateView, self).form_valid(form)

class ProfileDetailView(DetailView):
    """!
    Clase que permite a un usuario ver el perfil completo de otros usuarios

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 03-08-2018
    """

    model = User
    template_name = 'user/profile.detail.html'

    def dispatch(self, request, *args, **kwargs):
        """!
        Función que valida si el usuario del sistema tiene permisos para entrar a esta vista

        @author William Páez (paez.william8 at gmail.com)
        @date 03-08-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @param request <b>{object}</b> Objeto que contiene la petición
        @param *args <b>{tupla}</b> Tupla de valores, inicialmente vacia
        @param **kwargs <b>{dict}</b> Diccionario de datos, inicialmente vacio
        @return Redirecciona al usuario a la página de error de permisos si no es su perfil
        """

        if self.request.user.id == self.kwargs['pk'] and Profile.objects.filter(user=self.request.user):
            return super(ProfileDetailView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('base:error_403')

user/templates/user/login.html
{% extends 'base/base.html' %}
{% load i18n static %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Iniciar Sesión</li>
{% endblock %}
{% block content %}
  {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
      <p class="alert alert-danger">
        {{ error }}
      </p>
    {% endfor %}
  {% endif %}

  {% if user.is_authenticated %}
    <p class="alert alert-warning">
      {% blocktrans trimmed %}
        Ya se ha autenticado, pero no está autorizado a acceder a esta página.
        ¿Desea autenticarse con una cuenta diferente?
      {% endblocktrans %}
    </p>
  {% endif %}

  <div class="card card-login mx-auto mt-5">
    <div class="card-header">Iniciar Sesión</div>
    <div class="card-body">
      <form method="post" autocomplete="off" class="validate-form">
        {% csrf_token %}
        <div class="form-group">
          <label for="{{ form.username.auto_id }}">
            {{ form.username.label_tag }}
          </label>
          <input class="form-control" type="text" aria-describedby="emailHelp" name="username" required>
        </div>
        <div class="form-group">
          <label for="{{ form.password.auto_id }}">
            {{ form.password.label_tag }}
          </label>
          <input class="form-control" type="password" name="password" required>
        </div>
        <button class="btn btn-primary btn-block" type="submit">Entrar</button>
      </form>
      <div class="text-center">
        <a class="d-block small mt-3" href="{% url 'user:profile_create' %}">Registrarse</a>
        <a class="d-block small" href="{% url 'user:password_reset' %}">Olvidé mi contraseña</a>
      </div>
    </div>
  </div>
{% endblock %}

user/templates/user/password_change_done.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Cambiar Contraseña</li>
{% endblock %}
{% block content %}
  <div class="card mb-3">
    <div class="card-header"><i class="fa fa-unlock" aria-hidden="true"></i> Cambiar Contraseña</div>
    <div class="card-body">
      <p class="text-center">{% trans 'Your password was changed.' %}</p>
    </div>
  </div>
{% endblock %}

user/templates/user/password_change_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Cambiar Contraseña</li>
{% endblock %}
{% block content %}
  <div class="card mb-3">
    <div class="card-header"><i class="fa fa-unlock" aria-hidden="true"></i> Cambiar Contraseña</div>
    <form method="post" class="form form-horizontal validate-form">
      {% csrf_token %}
      <div class="card-body">
        <p>
          {% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}
        </p>
        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.old_password.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.old_password.auto_id }}">
                {{ form.old_password.label_tag }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.old_password }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.old_password.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.new_password1.auto_id }}">
                {{ form.new_password1.label_tag }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.new_password1 }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.new_password1.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
              <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.new_password2.auto_id }}">
                {{ form.new_password2.label_tag }}
              </label>
              <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                <div class="form-inline">
                  {{ form.new_password2 }}
                  <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                </div>
                {% include 'base/form.errors.html' with form_errors=form.new_password2.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer small text-right">
        <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip" >Enviar</button>
      </div>
    </form>
  </div>
{% endblock %}

user/templates/user/password_reset_complete.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Recuperar Contraseña Completado</li>
{% endblock %}
{% block content %}
  <div class="card md-3">
    <div class="card-header">Recuperar Contraseña</div>
    <div class="card-body">
      <p class="text-center">Su contraseña se reestableció correctamente</p>
    </div>
  </div>
{% endblock %}

user/templates/user/password_reset_confirm.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Nueva Contraseña</li>
{% endblock %}
{% block content %}
  <div class="card md-3">
    {% if validlink %}
      <div class="card-header">Nueva Contraseña</div>
      <form method="post">
        {% csrf_token %}
        <div class="card-body">
          <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
              <div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
                <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.new_password1.auto_id }}">
                  {{ form.new_password1.label_tag }}
                </label>
                <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                  <div class="form-inline">
                    {{ form.new_password1 }}
                    <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                  </div>
                  {% include 'base/form.errors.html' with form_errors=form.new_password1.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
              <div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
                <label class="col-xl-5 col-lg-5 col-md-5 col-sm-5 control-label" for="{{ form.new_password2.auto_id }}">
                  {{ form.new_password2.label_tag }}
                </label>
                <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7">
                  <div class="form-inline">
                    {{ form.new_password2 }}
                    <i class="fas fa-asterisk item-required" aria-hidden="true"></i>
                  </div>
                  {% include 'base/form.errors.html' with form_errors=form.new_password2.errors col_title_error='col-sm-4' col_msg_error='col-sm-8' %}
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer small text-right">
            <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Enviar' %}</button>
          </div>
        </div>
      </form>
    {% else %}
      <div class="card-header">Enlace Inválido</div>
      <div class="card-body">
        <p class="text-center">ESTE ENLACE YA HA SIDO UTILIZADO</p>
      </div>
    {% endif %}
  </div>
{% endblock %}

user/templates/user/password_reset_done.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Recuperar Contraseña</li>
{% endblock %}
{% block content %}
  <div class="card md-3">
    <div class="card-header">Recuperar Contraseña</div>
    <div class="card-body">
      <p>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</p>
    </div>
  </div>
{% endblock %}

user/templates/user/password_reset_email.html
Solicitaste reestablecimiento de contraseña.
Click en el siguiente link para crear una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

user/templates/user/password_reset_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item acive">Recuperar Contraseña</li>
{% endblock %}
{% block content %}
  <div class="card card-login mx-auto mt-5">
    <div class="card-header">Recuperar Contraseña</div>
    <div class="card-body">
      <div class="text-center mb-4">
        <h4>¿Olvidaste tu contraseña?</h4>
        <p>Ingrese su dirección de correo electrónico y le enviaremos instrucciones sobre cómo restablecer su contraseña.</p>
      </div>
      <form>
        <div class="form-group">
            <label for="{{ form.email.auto_id }}">{{ form.email.label_tag }}</label>
            <input type="email" id="id_email" class="form-control" required="required" autofocus="autofocus" name="email">
        </div>
        <button type="submit" class="btn btn-primary btn-block" data-toggle="tooltip">Enviar</button>
      </form>
      <div class="text-center">
        <a class="d-block small mt-3" href="{% url 'user:profile_create' %}">Registrar una cuenta</a>
        <a class="d-block small" href="{% url 'user:login' %}">Iniciar Sesión</a>
      </div>
    </div>
  </div>
  <br>
{% endblock %}

user/templates/user/profile.detail.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="#">Usuario</a>
  </li>
  <li class="breadcrumb-item active">Detalle</li>
{% endblock %}
{% block content %}
  <div class="card mb-3">
    <div class="card-header">Detalle del Perfil</div>
    <div class="card-body">
      <p>Nombre de Usuario: {{ object.username }}</p>
      <p>Nombres: {{ object.first_name }}</p>
      <p>Apellidos: {{ object.last_name }}</p>
      <p>Correo Electrónico: {{ object.email }}</p>
      <p>Teléfono: {{ object.profile.phone }}</p>
    </div>
  </div>
{% endblock %}