base/urls.py
from django.urls import path, re_path, include
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from rest_framework import routers
from .views import CountryViewSet

app_name = 'base'

router = routers.DefaultRouter()
router.register(r'countries', CountryViewSet)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name = 'error_403'),

    path('api/', include(router.urls)),
]

## URLs de peticiones AJAX
urlpatterns += [
    re_path(r'^ajax/combo-update/?$', ComboUpdateView.as_view(), name='combo_update'),
]

person/urls.py
from django.urls import path
from .views import PersonListView, PersonCreateView, PersonUpdateView, PersonDeleteView
from django.contrib.auth.decorators import login_required

app_name = 'person'

urlpatterns = [
    path('list/', login_required(PersonListView.as_view()), name='list'),
    path('create/', login_required(PersonCreateView.as_view()), name='create'),
    path('update/<int:pk>/', login_required(PersonUpdateView.as_view()), name='update'),
    path('delete/<int:pk>/', login_required(PersonDeleteView.as_view()), name='delete'),
]

user/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from .views import ProfileCreateView, ProfileUpdateView, ProfileDetailView

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('reset/password_reset/', views.PasswordResetView.as_view(template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html', success_url = reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
        success_url = reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),
    path('password-change/', login_required(views.PasswordChangeView.as_view(template_name='user/password_change_form.html',
        success_url = reverse_lazy('user:password_change_done'))), name='password_change'),
    path('password-change-done/', login_required(views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html')),
        name='password_change_done'),
    path('profile-create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile-update/<int:pk>/', login_required(ProfileUpdateView.as_view()), name='profile_update'),
    path('profile-detail/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail')
]

base/models.py
from django.db import models

# Create your models here.

class Country(models.Model):
    """!
    Clase que contiene los paises

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    ## Nombre del pais
    name = models.CharField(max_length=80)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del país
        """

        return self.name

class State(models.Model):
    """!
    Clase que contiene los estados

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    ## Nombre del Estado
    name = models.CharField(max_length=50)

    ## Pais en donde esta ubicado el Estado
    country = models.ForeignKey(Country,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del estado
        """

        return self.name

class Municipality(models.Model):
    """!
    Clase que contiene los municipios

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    ## Nombre del Municipio
    name = models.CharField(max_length=50)

    ## Estado en donde se encuentra el Municipio
    state = models.ForeignKey(State,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre del municipio
        """

        return self.name

class City(models.Model):
    """!
    Clase que contiene las ciudades

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    ## Nombre de la Ciudad
    name = models.CharField(max_length=50)

    ## Estado en donde se encuentra ubicada la Ciudad
    state = models.ForeignKey(State,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre de la ciudad
        """

        return self.name

class Parish(models.Model):
    """!
    Clase que contiene las parroquias

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    ## Nombre de la Parroquia
    name = models.CharField(max_length=50)

    ## Municipio en el que se encuentra ubicada la Parroquia
    municipality = models.ForeignKey(Municipality,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (paez.william8 at gmail.com)
        @date 06-07-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return string <b>{object}</b> Objeto con el nombre de la parroquia
        """

        return self.name

base/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from rest_framework import viewsets
from .serializers import CountrySerializer
from .models import Country, State
from rest_framework import generics

# Create your views here.

class HomeView(TemplateView):
    """!
    Clase que muestra la página inicial

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    template_name = 'base/base.html'

class Error403View(TemplateView):
    """!
    Clase que muestra la página de error de permisos

    @author William Páez (paez.william8 at gmail.com)
    @copyright <a href='​http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 06-07-2018
    """

    template_name = 'base/error.403.html'

class CountryViewSet(viewsets.ReadOnlyModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Country.objects.all()
    serializer_class = CountrySerializer
    #http_method_names = ['get']

base/templates/base/alert.messages.html
{% load i18n %}
{% for message in messages %}
  {% if message %}
    <script type="text/javascript">
      var msg = "{{ message }}";
      var modal = bootbox.dialog({
        message: msg,
        title: "{% trans 'Aviso' %}",
        buttons: {
          success: {
            label: "{% trans 'Cerrar' %}",
            className: "btn-info",
            callback: function() {

            }
          }
        }
      });
      $(modal).find(".bootbox-body").addClass('text-justify');
    </script>
  {% endif %}
{% endfor %}

base/templates/base/base.html
<!DOCTYPE html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"es-ve" }}">
  {% include 'base/head.html' %}
  <body id="page-top">
    {% include 'base/navbar.html' %}
    <div id="wrapper">
      {% include 'base/sidebar.html' %}
      <div id="content-wrapper">
        <div class="container-fluid">

          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'base:home' %}">Inicio</a>
            </li>
            {% block breadcrumb %}

            {% endblock %}
          </ol>

          <div class="row">
            <div class="col-12">
              <h1>{% block content_header_title %}{% endblock %}</h1>
            </div>
          </div>
          {% block content %}
            <div class="row">
              <div class="col-12">
                <center>
                  {% if request.user.is_authenticated %}
                    <p>Bienvenido {{ request.user.username }}.</p>
                  {% else %}
                    <p>Bienvenido al sistema.</p>
                    <p>Inicie sesión para registrar los datos.</p>
                  {% endif %}
                </center>
              </div>
            </div>
          {% endblock %}
        </div>
        {% include 'base/footer.info.html' %}
      </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
    {% include 'base/footer.html' %}
    {% block extra_footer %}

    {% endblock %}
    <script type="text/javascript">
      $(document).ready(function()
        {
          //obtiene la url actual del sistema
          var route = "{{ request.path }}";
          //rutas de la app persona
          var pe = "/person/list/";

          if( route == "/" )
          {
            $("#ba").addClass("active");
          }
          else if( route == pe )
          {
            $("#pe").addClass("active");
          }
        });
    </script>
  </body>
</html>

base/templates/base/error.403.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}<br>{% endblock %}
{% block content %}
  <div class="card md-3">
    <div class="card-header">Error</div>
    <div class="card-body">
      <h3 class="text-center"><i class="fa fa-warning text-red"></i> Oops! No tiene permiso de acceso a esta página.</h3>
      <p class="text-center">
        No puedes acceder a la pagina que buscas.
        Puedes <b><a href="{% url 'base:home' %}">retornar a inicio</a></b> o solicitar al administrador permisos de acceso.
      </p>
    </div>
  </div>
{% endblock %}

base/templates/base/footer.html
{% load static from staticfiles %}
{% load i18n %}
<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/popper.js/dist/umd/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/jquery.easing/jquery.easing.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/select2/dist/js/select2.full.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/jquery-mask-plugin/dist/jquery.mask.min.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  var URL_COMBO_UPDATE = "{% url 'base:combo_update' %}";
</script>
<script src="{% static 'js/ajax.request.js' %}" type="text/javascript"></script>
<script src="{% static 'js/functions.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net/js/jquery.dataTables.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/dataTables.buttons.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.html5.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.flash.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.print.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/jszip/dist/jszip.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/pdfmake/build/pdfmake.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/pdfmake/build/vfs_fonts.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/bootbox/bootbox.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/sb-admin.min.js' %}" type="text/javascript"></script>
{% include 'base/alert.messages.html' %}
<script type="text/javascript">
  $(document).ready(function(){
    //muestra los mensajes centrados
    $('[data-toggle="tooltip"]').tooltip();

    //para agregar el select2 en los respectivos campos de tipo select
    $(".select2").select2();

    $.extend( true, $.fn.dataTable.defaults, {
      "language": {
        "sProcessing":     "Procesando...",
        "sLengthMenu":     "Mostrar _MENU_ registros",
        "sZeroRecords":    "No se encontraron resultados",
        "sEmptyTable":     "Ningún dato disponible en esta tabla",
        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix":    "",
        "sSearch":         "Buscar:",
        "sUrl":            "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
          "sFirst":    "Primero",
          "sLast":     "Último",
          "sNext":     "Siguiente",
          "sPrevious": "Anterior"
        },
        "oAria": {
          "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        },
      },
      "scrollX": true,
    });
  });
</script>

base/templates/base/footer.info.html
<footer class="sticky-footer">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      Copyleft <i class="far fa-copyright fa-flip-horizontal"></i> Ejemplo Django {% now 'Y' %}
    </div>
  </div>
</footer>

base/templates/base/form.errors.html
{% load i18n %}
{% if form_errors %}
  <div class="error-notice">
    <div class="oaerror danger">
      <div class="row">
        <div class="{% if not col_title_error %}col-sm-3{% else %}{{ col_title_error }}{% endif %}">
          <strong>{% trans 'Error' %}</strong>
        </div>
        <div class="{% if not col_msg_error %}col-sm-9{% else %}{{ col_msg_error }}{% endif %}">
          {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
        </div>
      </div>
    </div>
  </div>
{% endif %}

base/templates/base/head.html
{% load static from staticfiles %}
{% load i18n %}
<head>
	<meta charset="UTF-8">
	<title>{% trans 'Ejemplo Django' %}</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
	<meta name="description" content="{% trans 'Ejemplo de un crud en django' %}">
	<meta name="author" content="William Páez (paez.william8 at gmail.com)">
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/select2/dist/css/select2.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/sb-admin.min.css' %}">
	{% block extra_head %}

	{% endblock %}
</head>

base/templates/base/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark static-top" id="mainNav">
  <a class="navbar-brand mr-1" href="{% url 'base:home' %}">Ejemplo Django</a>
  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
    <li class="nav-item dropdown no-arrow">
      {% if request.user.is_authenticated %}
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
          {{ request.user.username }}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="{% url 'user:profile_detail' request.user.id %}">Detalles</a>
          <a class="dropdown-item" href="{% url 'user:profile_update' request.user.id %}">Perfil</a>
          <a class="dropdown-item" href="{% url 'user:password_change' %}">Cambiar Contraseña</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'user:logout' %}"><i class="fas fa-sign-out-alt"></i>Salir</a>
        </div>
      {% else %}
        <a class="nav-link" href="{% url 'user:login' %}">
          <i class="fas fa-sign-in-alt"></i> Iniciar Sesión
        </a>
      {% endif %}
    </li>
  </ul>
</nav>

base/templates/base/sidebar.html
<ul class="sidebar navbar-nav">
  <li class="nav-item" id="ba">
    <a class="nav-link" href="{% url 'base:home' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Inicio</span>
    </a>
  </li>
  {% if request.user.is_authenticated %}
    <li class="nav-item" id="pe">
      <a class="nav-link" href="{% url 'person:list' %}">
        <i class="fas fa-fw fa-user-plus"></i>
        <span>Personas</span>
      </a>
    </li>
  {% endif %}
</ul>